FROM node:22-bookworm-slim AS assets

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build


FROM dunglas/frankenphp:php8.3-bookworm

WORKDIR /app

RUN install-php-extensions \
    pdo_sqlite \
    mbstring \
    bcmath \
    opcache \
    zip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . .

COPY --from=assets /app/public/build ./public/build

RUN composer install \
    --no-dev \
    --optimize-autoloader \
    --no-interaction

RUN mkdir -p \
    storage/framework/cache \
    storage/framework/sessions \
    storage/framework/views \
    bootstrap/cache

RUN chmod -R 775 storage bootstrap/cache

CMD ["sh", "-c", "frankenphp php-server -r public/ --listen :${PORT:-80}"]
